name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install micropython dependencies
        run: |
          git clone https://github.com/pyenv/pyenv.git ~/.pyenv
          pyenv install micropython-1.19.1
          pyenv local micropython-1.19.1
          micropython -m upip install -r requirements.txt -t 'firmware/'
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          directory: 'firmware/'
          filename: 'release.zip'
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: |
          npm install @semantic-release/commit-analyzer \
                      @semantic-release/release-notes-generator \
                      @semantic-release/github \
                      semantic-release
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release -e ./.github/.releaserc.json
